import {
  SimpleGrid,
  Table,
  Thead,
  Tbody,
  Tr,
  Th,
  Td,
  Box,
} from "@chakra-ui/react";

function App() {
  return (
    <>
      <SimpleGrid gap={5} columns={1}>
        <Box>
          <Table>
            <Thead>
              <Tr>
                <Th>Lorem.</Th>
                <Th>Voluptates?</Th>
                <Th>Natus!</Th>
                <Th>Ipsam?</Th>
              </Tr>
            </Thead>
            <Tbody>
              <Tr>
                <Td>Lorem.</Td>
                <Td>Accusamus?</Td>
                <Td>Doloremque?</Td>
                <Td>Vero.</Td>
              </Tr>
              <Tr>
                <Td>Lorem.</Td>
                <Td>Ratione?</Td>
                <Td>Minima?</Td>
                <Td>Modi?</Td>
              </Tr>
              <Tr>
                <Td>Lorem.</Td>
                <Td>Magni.</Td>
                <Td>Eum?</Td>
                <Td>Cum!</Td>
              </Tr>
              <Tr>
                <Td>Lorem.</Td>
                <Td>Molestiae.</Td>
                <Td>Voluptatibus?</Td>
                <Td>Aliquid!</Td>
              </Tr>
              <Tr>
                <Td>Lorem.</Td>
                <Td>Natus!</Td>
                <Td>Ut!</Td>
                <Td>Facere.</Td>
              </Tr>
            </Tbody>
          </Table>
        </Box>
        <Box>
          <Table variant="striped" colorScheme="red">
            <Thead>
              <Tr>
                <Th>Lorem.</Th>
                <Th>Repellat?</Th>
                <Th>Incidunt.</Th>
                <Th>Labore!</Th>
              </Tr>
            </Thead>
            <Tbody>
              <Tr>
                <Td>Lorem.</Td>
                <Td>Aspernatur!</Td>
                <Td>Repudiandae.</Td>
                <Td>Distinctio.</Td>
              </Tr>
              <Tr>
                <Td>Lorem.</Td>
                <Td>Facilis.</Td>
                <Td>Natus!</Td>
                <Td>Aliquid?</Td>
              </Tr>
              <Tr>
                <Td>Lorem.</Td>
                <Td>Architecto.</Td>
                <Td>Rerum.</Td>
                <Td>Eligendi?</Td>
              </Tr>
              <Tr>
                <Td>Lorem.</Td>
                <Td>Ipsam!</Td>
                <Td>Alias.</Td>
                <Td>Ducimus?</Td>
              </Tr>
              <Tr>
                <Td>Lorem.</Td>
                <Td>Possimus?</Td>
                <Td>Consequuntur.</Td>
                <Td>Esse?</Td>
              </Tr>
            </Tbody>
          </Table>
        </Box>
      </SimpleGrid>
    </>
  );
}

export default App;
